set_property SRC_FILE_INFO {cfile:{G:/My Drive/_iCloud/EGEC Classes/HDL/Verilog/1HzLEDBlink/1HzLEDBlink/1HzLEDBlink.srcs/constrs_1/new/constraints.xdc} rfile:../../../1HzLEDBlink.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports led]
